DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller
DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.urls import include, re_path

    urlpatterns = [
        re_path(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.urls import patterns, re_path
    except ImportError:
        from django.urls.defaults import patterns, re_path

    urlpatterns = patterns('',
        re_path(r'^controller/$', get_ueditor_controller)
    )

aboutApp/urls.py
from django.urls import path
from . import views

app_name = 'aboutApp'  # 设置应用名

urlpatterns = [
    path('survey/', views.survey, name='survey'),   # 企业概况
    path('honor/', views.honor, name='honor'),      # 荣誉资质
]

hengDaProject/urls.py
from django.contrib import admin
from django.urls import path
from homeApp.views import home # 导入首页对应的视图处理函数
from django.conf.urls import include # 导入include函数


urlpatterns = [
    path('admin/', admin.site.urls),                        # 管理员
    path('', home, name='home'),                            # 首页
    path('aboutApp/', include('aboutApp.urls')),            # 公司简介
    path('contactApp/', include('contactApp.urls')),        # 人才招聘
    path('newsApp/', include('newsApp.urls')),              # 新闻动态
    path('productsApp/', include('productsApp.urls')),      # 产品中心
    path('scienceApp/', include('scienceApp.urls')),        # 科研基地
    path('serviceApp/', include('serviceApp.urls')),        # 服务支持
    path('ueditor/',include('DjangoUeditor.urls')),         # 富文本服务
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

newsApp/urls.py
from django.urls import path
from . import views

app_name = 'newsApp'

urlpatterns = [
    path('news/<str:newName>/', views.news, name='news'), # 新闻列表
    path('newDetail/<int:id>/', views.newDetail, name='newDetail'), # 新闻列表
]

productsApp/urls.py
from django.urls import path
from . import views

app_name = 'productsApp'

urlpatterns = [
    path('products/<str:productName>/', views.products, name='products'),
    path('productDetail/<int:id>/', views.productDetail, name='productDetail'), #添加产品详情路由
]

homeApp/models.py
from django.db import models

# Create your models here.

homeApp/views.py
from django.shortcuts import render
from newsApp.models import MyNew
from django.db.models import Q
from productsApp.models import Product

from django.views.decorators.cache import cache_page
@cache_page(60 * 15) # 单位：秒数，这里指缓存 15 分钟
def home(request):
    # 新闻展报
    newList = MyNew.objects.all().filter(~Q(newType='通知公告')).order_by('-publishDate')
    postList = set()
    postNum = 0
    for s in newList:
        if s.photo:
            postList.add(s)
            postNum += 1
        if postNum == 3:  # 只截取最近的3个展报
            break

    # 新闻列表
    if (len(newList) > 7):
        newList = newList[0:7]

    # 通知公告
    noteList = MyNew.objects.all().filter(
        Q(newType='新闻动态')).order_by('-publishDate')
    if (len(noteList) > 4):
        noteList = noteList[0:4]

    # 产品列表
    productList = Product.objects.all().order_by('-views')
    if(len(productList)>4):
        productList = productList[0:4]

    # 返回结果
    return render(request, 'home.html', {
        'active_menu': 'home',
        'postList': postList,
        'newList': newList,
        'noteList': noteList,
        'productList':productList,

    })

homeApp/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}
首页
{% endblock %}
{% block content %}
<link href="{% static 'css/home.css' %}" rel="stylesheet">
<script src="{% static 'js/jqthumb.min.js' %}"></script>
<!-- 广告横幅 -->
<div id="ad" class="carousel slide" data-ride="carousel" data-interval="5000">
    <ol class="carousel-indicators">
        <li data-target="#ad" data-slide-to="0" class="active"></li>
        <li data-target="#ad" data-slide-to="1"></li>
        <li data-target="#ad" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="item active">
            <img src="{% static 'img/img22.jpg' %}" alt="广告横幅1">
        </div>
        <div class="item">
            <img src="{% static 'img/img21.jpg' %}" alt="广告横幅2">
        </div>
        <div class="item">
            <img src="{% static 'img/img20.jpg' %}" alt="广告横幅3">
        </div>
    </div>
    <a class="left carousel-control" href="#ad" data-slide="prev"><span
            class="glyphicon glyphicon-chevron-left"></span></a>
    <a class="right carousel-control" href="#ad" data-slide="next"><span
            class="glyphicon glyphicon-chevron-right"></span></a>
</div>
<!-- 主体内容 -->
<div class="container">
	<div class="row row-3">
		<div class="col-md-4">
			<!-- 企业概况 -->
            <span class="part1">
                <a href="{% url 'aboutApp:survey' %}">重庆欢迎你</a>
            </span>
            <span class="part1 en">
                &nbsp;&nbsp;
            </span>
            <div class="line1">
                <div class="line2 theme"></div>
            </div>
            <div>
                <img class="img-responsive" src="{% static 'img/85.jpg' %}">
                <p class="text1">
                    初见春暖花开时，游历山青水色中
                </p>
            </div>
		</div>
		<div class="col-md-8">
			<!-- 新闻动态 -->
            <span class="part1">
                <a href="#">新闻动态</a>
            </span>
            <span class="part1 en">
                &nbsp;&nbsp;
            </span>
            <a class="btn btn-default btn-xs more-btn" href="{% url 'newsApp:news' 'company' %}">+&nbsp;更多</a>
            <div class="line1">
                <div class="line2 theme"></div>
            </div>
            <div class="col-md-5">
                <div id="myCarousel" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators nav-point">
                        {% for post in postList %}
                        <li data-target="#myCarousel" data-slide-to="{{forloop.counter0}}" {% if forloop.first %} class="active" {% endif %}>
                        </li>
                        {% endfor %}
                    </ol>
                    <!-- 轮播（Carousel）项目 -->
                    <div class="carousel-inner">
                        {% for post in postList %}
                        <div {% if forloop.first %} class="item active" {% else %} class="item" {% endif %} style="background-size:cover;">
                            <a href="{% url 'newsApp:newDetail' post.id %}">
                                <img src="{{post.photo.url}}" class="img-responsive" onload="DrawImage(this)">
                            <div class="carousel-caption nav-title">{{post.title}}</div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-md-7">
                <ul class="list-unstyled list-new">
                    {% for mynew in newList %}
                    <li>
                        <a href="{% url 'newsApp:newDetail' mynew.id %}">
                            {{mynew.title|truncatechars:"25"}}</a>
                        <span>【{{mynew.publishDate|date:"Y-m-d"}}】</span>
                    </li>
                    {% endfor %}
                </ul>
            </div>
		</div>
	</div>
	
	<div class="row row-3">
		<!-- 产品中心 -->
		<div class="col-md-12 col-pro">
            <div class="row">
                <div class="col-md-12">
                    <span class="part1">
                        <a href="{% url 'productsApp:products' 'robot' %}">跟团游</a>
                    </span>
                    <span class="part1 en">
                        &nbsp;&nbsp;
                    </span>
                    <a class="btn btn-default btn-xs more-btn" href="{% url 'productsApp:products' 'robot' %}">+&nbsp;更多</a>
                    <div class="line1" style="margin-bottom:5px;">
                        <div class="line2 theme"></div>
                    </div>
                </div>

                <div class="col-md-12 col-pro">
                    <div id="Carousel" class="carousel slide" style="margin-bottom:30px">
                        <ol class="carousel-indicators" style="display:none;">
                            <li data-target="#Carousel" data-slide-to="0" class="active"></li>
                        </ol>
                        <div class="carousel-inner">
                            <div class="item active">
                                <div class="row">
                                    {% for product in productList %}
                                    <div class="col-md-3 pro-images">
                                        <a href="{% url 'productsApp:productDetail' product.id %}" class="thumbnail">
                                            {% for img in product.productImgs.all %}
                                            {% if forloop.first %}
                                            <img src="{{img.photo.url}}" alt="产品图片" class="img-responsive" onload="DrawImage(this)">
                                            {% endif %}
                                            {% endfor %}
                                        </a>
                                        <div class="carousel-caption nav-title">{{product.title}}</div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>	
	<div class="row row-3">
		<!-- 友情链接 -->
		<div class="col-md-12">
		</div>
	</div>
</div>

<script>
    //处理缩略图
    function DrawImage(hotimg) {
        $(hotimg).jqthumb({
            width: '100%',   // 宽度
            height: '250px', // 高度
            zoom: '1',       // 缩放比例
            method: 'auto'   // 提交方法，用于不同的浏览器环境，默认为‘auto’
        });
    }
</script>
{% endblock %}