DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller
DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.urls import include, re_path

    urlpatterns = [
        re_path(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.urls import patterns, re_path
    except ImportError:
        from django.urls.defaults import patterns, re_path

    urlpatterns = patterns('',
        re_path(r'^controller/$', get_ueditor_controller)
    )

aboutApp/urls.py
from django.urls import path
from . import views

app_name = 'aboutApp'  # 设置应用名

urlpatterns = [
    path('survey/', views.survey, name='survey'),   # 企业概况
    path('honor/', views.honor, name='honor'),      # 荣誉资质
]

hengDaProject/urls.py
from django.contrib import admin
from django.urls import path
from homeApp.views import home # 导入首页对应的视图处理函数
from django.conf.urls import include # 导入include函数


urlpatterns = [
    path('admin/', admin.site.urls),                        # 管理员
    path('', home, name='home'),                            # 首页
    path('aboutApp/', include('aboutApp.urls')),            # 公司简介
    path('contactApp/', include('contactApp.urls')),        # 人才招聘
    path('newsApp/', include('newsApp.urls')),              # 新闻动态
    path('productsApp/', include('productsApp.urls')),      # 产品中心
    path('scienceApp/', include('scienceApp.urls')),        # 科研基地
    path('serviceApp/', include('serviceApp.urls')),        # 服务支持
    path('ueditor/',include('DjangoUeditor.urls')),         # 富文本服务
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

newsApp/urls.py
from django.urls import path
from . import views

app_name = 'newsApp'

urlpatterns = [
    path('news/<str:newName>/', views.news, name='news'), # 新闻列表
    path('newDetail/<int:id>/', views.newDetail, name='newDetail'), # 新闻列表
]

productsApp/urls.py
from django.urls import path
from . import views

app_name = 'productsApp'

urlpatterns = [
    path('products/<str:productName>/', views.products, name='products'),
    path('productDetail/<int:id>/', views.productDetail, name='productDetail'), #添加产品详情路由
]

scienceApp/urls.py
from django.urls import path
from . import views

app_name = 'scienceApp'

urlpatterns = [
    path('science/', views.science, name='science'),  # 科研基地
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>重庆市旅游网|{% block title %}{% endblock %} </title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>

<body>
    <div class="container top">
        <div class="row">
            <div class="col-md-6">
                <a>
                    <img class="img-responsive" src="{% static 'img/84.jpg' %}" style="width: 400px; height: 100px;">
                </a>
            </div>
            <div class="col-md-3 hidden-xs">
                <a class="phone ant">
                    <span class="glyphicon glyphicon-star"></span>电话：023-67705583 &nbsp; &nbsp;
                </a>
            </div>
            <div class="col-md-3 hidden-xs">
                <a class="mail ant">
                    <span class="glyphicon glyphicon-star"></span>邮编：401123
                </a>
            </div>
        </div>
    </div>


    <!-- 导航条 -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example"
                    aria-expanded="false">
                    <span>导航栏</span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="bs-example">
                <ul class="nav navbar-nav" style="width:100%;">
                    <li class="nav-top" id='home'>
                        <a href="{% url 'home' %}">首页</a>
                    </li>
                    <li class="dropdown nav-top" id='about'>
                        <a href="#" class="dropdown-toggle on" data-toggle="dropdown">
                            旅游景点</a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'aboutApp:survey' %}">5A级景区</a></li>
                            <li><a href="{% url 'aboutApp:honor' %}">精彩推荐</a></li>
                        </ul>
                    </li>
                    <li class="dropdown nav-top">
                        <a href="#" class="dropdown-toggle on" data-toggle="dropdown">
                            新闻动态</a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'newsApp:news' 'company' %}">文旅要闻</a></li>
                            <li><a href="{% url 'newsApp:news' 'notice' %}">宣传动态</a></li>
                        </ul>
                    </li>
                    <li class="dropdown nav-top" id='products'>
                        <a href="#" class="dropdown-toggle on" data-toggle="dropdown">
                            跟团游</a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'productsApp:products' 'robot' %}">
                                    一日游</a></li>
                            <li><a href="{% url 'productsApp:products' 'monitor' %}">
                                    多日游</a></li>
                            <li><a href="{% url 'productsApp:products' 'face' %}">
                                    亲子游</a></li>
                        </ul>
                    </li>
                    <li class="nav-top" id='science'>
                        <a href="{% url 'scienceApp:science' %}">咨询</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="line"></div>

    {% block content %}
    {% endblock %}

    <div class="row" id="map-footer">
        <div class="col-md-2">
            <dl>
                <dt>旅游景点</dt>
                <dd><a href="{% url 'aboutApp:survey' %}">5A级景区</a></dd>
                <dd><a href="{% url 'aboutApp:honor' %}">精彩推荐</a></dd>
            </dl>
        </div>
        <div class="col-md-2">
            <dl>
                <dt>旅游团推荐</dt>
                <dd><a href="{% url 'productsApp:products' 'robot' %}">一日游</a></dd>
                <dd><a href="{% url 'productsApp:products' 'monitor' %}">多日游</a></dd>
                <dd><a href="{% url 'productsApp:products' 'face' %}">亲子游</a></dd>
            </dl>
        </div>
        <div class="col-md-2">
            <dl>
                <dt>新闻动态</dt>
                <dd><a href="{% url 'newsApp:news' 'company' %}">文旅要闻</a></dd>
                <dd><a href="{% url 'newsApp:news' 'notice' %}">宣传动态</a></dd>
            </dl>
        </div>
        <div class="col-md-2">
            <dl>
                <dt>欢迎咨询</dt>
                <dd><a href="{% url 'scienceApp:science' %}">咨询</a></dd>
            </dl>
        </div>
        <div class="col-md-4" id="wx">
            <p>扫描二维码，关注我们</p>
            <img class="qrimg" src="{% static 'img/qr.jpg' %}" alt="wx">
            <p>客服热线：<b style="font-size:20px">400 111 2222</b></p>
        </div>
    </div>

    <script>
        $(function () {
            $(".dropdown").mouseover(function () {
                $(this).addClass("open");
            });
            $(".dropdown").mouseleave(function () {
                $(this).removeClass("open");
            });
        });
    </script>

    <script type="text/JavaScript">
        $('#{{active_menu}}').addClass("active");
    </script>

    <script type="text/JavaScript">
        $('#{{sub_menu}}').addClass("active");
    </script>
</body>

</html>